services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: namder-admin
      POSTGRES_PASSWORD: namder-password
      POSTGRES_DB: namder-db
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: